require 'spnet/version'
require 'spnet/in_port'
require 'spnet/out_port'
require 'spnet/block'

require 'spnet/ports/signal_in_port'
require 'spnet/ports/signal_out_port'
require 'spnet/ports/value_in_port'
require 'spnet/ports/value_out_port'
require 'spnet/ports/command_in_port'
require 'spnet/ports/command_out_port'
